Name: clblas-intel
Version:  d16f7b3git 
Release: 1%{?dist}
Summary: clBLAS for Intel processors using Beignet runtime on Fedora 24

License: Apache License, Version 2.0
URL: https://github.com/clMathLibraries/clBLAS
Source0: https://github.com/clMathLibraries/clBLAS/archive/master.zip

BuildRequires: cmake
BuildRequires: beignet-devel
BuildRequires: blas-devel
BuildRequires: boost-devel
BuildRequires: ocl-icd-devel
BuildRequires: boost-static

%description
clBLAS is a library that can make use of GPUs to offload basic linear algebra subroutine libraries.
The version here is built using the Intel Beignet openCL runtime which will work on Intel CPUs with
integrated GPUs.

%prep
rm -rf clBLAS-master
unzip %{SOURCE0}

%build
cmake clBLAS-master/src/ -DBUILD_TEST=off -DBUILD_KTEST=off -DCMAKE_BUILD_TYPE=Debug -DBOOST_LIBRARYDIR=/usr/local/lib64/
make %{?_smp_mflags}

%install
make install DESTDIR=%{buildroot}

%check
ctest -V %{?_smp_mflags}

%clean
rm -rf %{buildroot} 

%files
/usr/local/lib64/src/clAmdBlas.h
/usr/local/lib64/src/clBLAS.version.h.in
/usr/local/lib64/src/clAmdBlas.version.h
/usr/local/lib64/src/clBLAS-complex.h
/usr/local/lib64/src/CMakeLists.txt
/usr/local/lib64/src/clBLASConfig.cmake.in
/usr/local/lib64/src/FindNetlib.cmake
/usr/local/lib64/src/targetver.h
/usr/local/lib64/src/clBLASConfigVersion.cmake.in
/usr/local/lib64/src/FindOpenCL.cmake
/usr/local/lib64/src/clBLAS.def
/usr/local/lib64/src/flags_public.txt
/usr/local/lib64/src/clBLAS.h
/usr/local/lib64/src/client/clfunc_common.hpp
/usr/local/lib64/src/client/clfunc_xher2k.hpp  
/usr/local/lib64/src/client/clfunc_xtrmm.hpp
/usr/local/lib64/src/client/statisticalTimer.cpp
/usr/local/lib64/src/client/clfunc_xgemm.hpp
/usr/local/lib64/src/client/clfunc_xher.hpp
/usr/local/lib64/src/client/clfunc_xtrmv.hpp
/usr/local/lib64/src/client/statisticalTimer.h
/usr/local/lib64/src/client/clfunc_xgemv.hpp
/usr/local/lib64/src/client/clfunc_xherk.hpp
/usr/local/lib64/src/client/clfunc_xtrsm.hpp
/usr/local/lib64/src/client/stdafx.cpp
/usr/local/lib64/src/client/clfunc_xgerc.hpp
/usr/local/lib64/src/client/clfunc_xsymm.hpp
/usr/local/lib64/src/client/clfunc_xtrsv.hpp  
/usr/local/lib64/src/client/stdafx.h
/usr/local/lib64/src/client/clfunc_xger.hpp
/usr/local/lib64/src/client/clfunc_xsymv.hpp
/usr/local/lib64/src/client/clGemm.h
/usr/local/lib64/src/client/targetver.h
/usr/local/lib64/src/client/clfunc_xgeru.hpp
/usr/local/lib64/src/client/clfunc_xsyr2.hpp   
/usr/local/lib64/src/client/client.cpp
/usr/local/lib64/src/client/testPerfWrapper.cpp
/usr/local/lib64/src/client/clfunc_xhemm.hpp
/usr/local/lib64/src/client/clfunc_xsyr2k.hpp
/usr/local/lib64/src/client/CMakeLists.txt
/usr/local/lib64/src/client/timer.cpp
/usr/local/lib64/src/client/clfunc_xhemv.hpp
/usr/local/lib64/src/client/clfunc_xsyr.hpp
/usr/local/lib64/src/client/ctimer.h
/usr/local/lib64/src/client/timer.hpp
/usr/local/lib64/src/client/clfunc_xher2.hpp
/usr/local/lib64/src/client/clfunc_xsyrk.hpp
/usr/local/lib64/src/client/makefile
/usr/local/lib64/src/include/binary_lookup.h
/usr/local/lib64/src/include/dblock_kgen.h
/usr/local/lib64/src/include/granulation.h
/usr/local/lib64/src/include/list.h
/usr/local/lib64/src/include/mutex.h
/usr/local/lib64/src/include/clblas_stddef.h
/usr/local/lib64/src/include/defbool.h
/usr/local/lib64/src/include/kern_cache.h
/usr/local/lib64/src/include/md5sum.h
/usr/local/lib64/src/include/rwlock.h
/usr/local/lib64/src/include/clkern.h
/usr/local/lib64/src/include/devinfo.h
/usr/local/lib64/src/include/kernel_extra.h
/usr/local/lib64/src/include/mempat.h
/usr/local/lib64/src/include/solver.h
/usr/local/lib64/src/include/cltypes.h
/usr/local/lib64/src/include/dis_warning.h
/usr/local/lib64/src/include/kerngen.h
/usr/local/lib64/src/include/msvc.h
/usr/local/lib64/src/include/trace_malloc.h
/usr/local/lib64/src/library/bingen.cmake
/usr/local/lib64/src/library/clBLAS.pc.in
/usr/local/lib64/src/library/CMakeLists.txt
/usr/local/lib64/src/library/OCLBinaryGenerator.cmake
/usr/local/lib64/src/library/common/clkern.c
/usr/local/lib64/src/library/common/kern_cache.c
/usr/local/lib64/src/library/common/kgen_loop_helper.c
/usr/local/lib64/src/library/common/mutex.c
/usr/local/lib64/src/library/common/devinfo.c
/usr/local/lib64/src/library/common/kerngen_core.c
/usr/local/lib64/src/library/common/list.c
/usr/local/lib64/src/library/common/rwlock.c
/usr/local/lib64/src/library/common/devinfo-cache.c
/usr/local/lib64/src/library/common/kgen_basic.c
/usr/local/lib64/src/library/common/md5sum.c
/usr/local/lib64/src/library/common/kgen_guard.c
/usr/local/lib64/src/library/common/misc.c
/usr/local/lib64/src/library/common/trace_malloc.c
/usr/local/lib64/src/library/common/gens/dblock_kgen.c
/usr/local/lib64/src/library/common/tests/CMakeLists.txt
/usr/local/lib64/src/library/common/tests/t_dblock_kgen.c
/usr/local/lib64/src/library/common/tests/t_gens_cache.c
/usr/local/lib64/src/library/tools/bingen/bingen.cpp
/usr/local/lib64/src/library/tools/bingen/CMakeLists.txt
/usr/local/lib64/src/library/tools/ktest/CMakeLists.txt
/usr/local/lib64/src/library/tools/ktest/ktest-common.h
/usr/local/lib64/src/library/tools/ktest/main.cpp
/usr/local/lib64/src/library/tools/ktest/step-dump.cpp
/usr/local/lib64/src/library/tools/ktest/var.h
/usr/local/lib64/src/library/tools/ktest/config-cmdline.cpp
/usr/local/lib64/src/library/tools/ktest/ktest.cpp
/usr/local/lib64/src/library/tools/ktest/step.h
/usr/local/lib64/src/library/tools/ktest/config.cpp
/usr/local/lib64/src/library/tools/ktest/ktest.h
/usr/local/lib64/src/library/tools/ktest/config.h
/usr/local/lib64/src/library/tools/ktest/ktest-patterns.h
/usr/local/lib64/src/library/tools/ktest/step.cpp
/usr/local/lib64/src/library/tools/ktest/var.cpp
/usr/local/lib64/src/library/tools/ktest/naive/naive_blas.cpp
/usr/local/lib64/src/library/tools/ktest/scripts/verify_ktest.bash
/usr/local/lib64/src/library/tools/ktest/steps/gemm.cpp
/usr/local/lib64/src/library/tools/ktest/steps/gemv.cpp
/usr/local/lib64/src/library/tools/ktest/steps/symv.cpp
/usr/local/lib64/src/library/tools/ktest/steps/syr2k.cpp
/usr/local/lib64/src/library/tools/ktest/steps/syrk.cpp
/usr/local/lib64/src/library/tools/ktest/steps/trmm.cpp
/usr/local/lib64/src/library/tools/ktest/steps/trsm.cpp
/usr/local/lib64/src/library/tools/ktest/steps/gemm.h
/usr/local/lib64/src/library/tools/ktest/steps/gemv.h
/usr/local/lib64/src/library/tools/ktest/steps/symv.h
/usr/local/lib64/src/library/tools/ktest/steps/syr2k.h
/usr/local/lib64/src/library/tools/ktest/steps/syrk.h
/usr/local/lib64/src/library/tools/ktest/steps/trmm.h
/usr/local/lib64/src/library/tools/ktest/steps/trsm.h
/usr/local/lib64/src/library/tools/OCLBinaryGenerator/CMakeLists.txt
/usr/local/lib64/src/library/tools/OCLBinaryGenerator/OCLBinaryGenerator.cpp
/usr/local/lib64/src/library/tools/tplgen/CMakeLists.txt
/usr/local/lib64/src/library/tools/tplgen/tplgen.cpp
/usr/local/lib64/src/library/tools/tune/CMakeLists.txt
/usr/local/lib64/src/library/tools/tune/fileio.h
/usr/local/lib64/src/library/tools/tune/storage_init.c
/usr/local/lib64/src/library/tools/tune/subdim.h
/usr/local/lib64/src/library/tools/tune/tune.c
/usr/local/lib64/src/library/tools/tune/dimension.c
/usr/local/lib64/src/library/tools/tune/storage_data.c
/usr/local/lib64/src/library/tools/tune/storage_io.c
/usr/local/lib64/src/library/tools/tune/toolslib.c
/usr/local/lib64/src/library/tools/tune/tune.h
/usr/local/lib64/src/library/tools/tune/fileio.c
/usr/local/lib64/src/library/tools/tune/storage_data.h
/usr/local/lib64/src/library/tools/tune/subdim.c
/usr/local/lib64/src/library/tools/tune/toolslib.h
/usr/local/lib64/src/library/blas/ixamax.c
/usr/local/lib64/src/library/blas/xdot.c
/usr/local/lib64/src/library/blas/xher2.c   
/usr/local/lib64/src/library/blas/xrotm.c   
/usr/local/lib64/src/library/blas/xsymv.c   
/usr/local/lib64/src/library/blas/xtrmv.c
/usr/local/lib64/src/library/blas/fill.cc   
/usr/local/lib64/src/library/blas/matrix.c      
/usr/local/lib64/src/library/blas/xgbmv.c   
/usr/local/lib64/src/library/blas/xher2k.c  
/usr/local/lib64/src/library/blas/xrotmg.c  
/usr/local/lib64/src/library/blas/xsyr2.c   
/usr/local/lib64/src/library/blas/xtrsm.cc
/usr/local/lib64/src/library/blas/scimage.c     
/usr/local/lib64/src/library/blas/xgemm2.c  
/usr/local/lib64/src/library/blas/xher.c    
/usr/local/lib64/src/library/blas/xscal.c   
/usr/local/lib64/src/library/blas/xsyr2k.c  
/usr/local/lib64/src/library/blas/xtrsv.c
/usr/local/lib64/src/library/blas/xgemm.cc  
/usr/local/lib64/src/library/blas/xherk.c   
/usr/local/lib64/src/library/blas/xscal.cc  
/usr/local/lib64/src/library/blas/xsyr.c
/usr/local/lib64/src/library/blas/xgemv.c   
/usr/local/lib64/src/library/blas/xhpmv.c   
/usr/local/lib64/src/library/blas/xshbmv.c  
/usr/local/lib64/src/library/blas/xsyrk.c
/usr/local/lib64/src/library/blas/impl.c    
/usr/local/lib64/src/library/blas/xasum.c       
/usr/local/lib64/src/library/blas/xger.c    
/usr/local/lib64/src/library/blas/xnrm2.c   
/usr/local/lib64/src/library/blas/xspmv.c   
/usr/local/lib64/src/library/blas/xtbmv.c
/usr/local/lib64/src/library/blas/xaxpy.c       
/usr/local/lib64/src/library/blas/xhemm.c   
/usr/local/lib64/src/library/blas/xrot.c    
/usr/local/lib64/src/library/blas/xswap.c   
/usr/local/lib64/src/library/blas/xtbsv.c
/usr/local/lib64/src/library/blas/init.c    
/usr/local/lib64/src/library/blas/xcopy.c       
/usr/local/lib64/src/library/blas/xhemv.c   
/usr/local/lib64/src/library/blas/xrotg.c   
/usr/local/lib64/src/library/blas/xsymm.c   
/usr/local/lib64/src/library/blas/xtrmm.c
/usr/local/lib64/src/library/blas/AutoGemm/AutoGemmParameters.py  
/usr/local/lib64/src/library/blas/AutoGemm/Common.py            
/usr/local/lib64/src/library/blas/AutoGemm/KernelSelection.py
/usr/local/lib64/src/library/blas/AutoGemm/AutoGemm.py            
/usr/local/lib64/src/library/blas/AutoGemm/Includes.py          
/usr/local/lib64/src/library/blas/AutoGemm/KernelsToPreCompile.py
/usr/local/lib64/src/library/blas/AutoGemm/AutoGemmTeardown.h     
/usr/local/lib64/src/library/blas/AutoGemm/KernelOpenCL.py      
/usr/local/lib64/src/library/blas/AutoGemm/README.txt
/usr/local/lib64/src/library/blas/AutoGemm/KernelParameters.py  
/usr/local/lib64/src/library/blas/AutoGemm/AutoGemmTools/AutoGemmPreCompileKernels.cpp  
/usr/local/lib64/src/library/blas/AutoGemm/AutoGemmTools/ProfileAutoGemm.cpp
/usr/local/lib64/src/library/blas/AutoGemm/AutoGemmTools/AutoGemmUtil.h                 
/usr/local/lib64/src/library/blas/AutoGemm/AutoGemmTools/TestAutoGemm.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/create_user_gemm_cl_kernels.py
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_NN_B0_MX048_NX048_KX08_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_NN_B1_MX048_NX048_KX08_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_NT_B0_MX048_NX048_KX08_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_NT_B1_MX048_NX048_KX08_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_TN_B0_MX048_NX048_KX08_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/dgemm_Col_TN_B1_MX048_NX048_KX08_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NN_B0_MX032_NX032_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NN_B0_MX064_NX064_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NN_B0_MX096_NX096_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NN_B1_MX032_NX032_KX16_BRANCH_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NN_B1_MX032_NX032_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NN_B1_MX064_NX064_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NN_B1_MX096_NX096_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B0_MX032_NX032_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B0_MX064_NX064_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B0_MX096_NX096_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B1_MX032_NX032_KX16_BRANCH_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B1_MX032_NX032_KX16_SINGLE_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B1_MX032_NX032_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B1_MX032_NX064_KX16_ROW_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B1_MX064_NX032_KX16_COL_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B1_MX064_NX064_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B1_MX096_NX096_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_NT_B1_MX128_NX128_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_TN_B0_MX032_NX032_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_TN_B0_MX064_NX064_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_TN_B0_MX096_NX096_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_TN_B1_MX032_NX032_KX16_BRANCH_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_TN_B1_MX032_NX032_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_TN_B1_MX064_NX064_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/sgemm_Col_TN_B1_MX096_NX096_KX16_src.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/UserGemmClKernels.cc
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/UserGemmClKernels.h
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/UserGemmKernelSourceIncludes.cpp
/usr/local/lib64/src/library/blas/AutoGemm/UserGemmKernelSources/UserGemmKernelSourceIncludes.h
/usr/local/lib64/src/library/blas/functor/bonaire.cc                 
/usr/local/lib64/src/library/blas/functor/gcn_zgemm.cc
/usr/local/lib64/src/library/blas/functor/functor.cc                 
/usr/local/lib64/src/library/blas/functor/gpu_dtrsm192.cc
/usr/local/lib64/src/library/blas/functor/functor_fill.cc            
/usr/local/lib64/src/library/blas/functor/gpu_dtrsm.cc
/usr/local/lib64/src/library/blas/functor/functor_selector.cc        
/usr/local/lib64/src/library/blas/functor/hawaii.cc
/usr/local/lib64/src/library/blas/functor/functor_xgemm.cc           
/usr/local/lib64/src/library/blas/functor/hawaii_dgemmChannelConflict.cc
/usr/local/lib64/src/library/blas/functor/functor_xscal.cc           
/usr/local/lib64/src/library/blas/functor/hawaii_dgemmSplitKernel.cc
/usr/local/lib64/src/library/blas/functor/functor_xscal_generic.cc   
/usr/local/lib64/src/library/blas/functor/hawaii_sgemmBig1024Kernel.cc
/usr/local/lib64/src/library/blas/functor/functor_xtrsm.cc           
/usr/local/lib64/src/library/blas/functor/hawaii_sgemmBranchKernel.cc
/usr/local/lib64/src/library/blas/functor/gcn_dgemm.cc               
/usr/local/lib64/src/library/blas/functor/hawaii_sgemmSplit64_32.cc
/usr/local/lib64/src/library/blas/functor/gcn_dgemmCommon.cc         
/usr/local/lib64/src/library/blas/functor/hawaii_sgemmSplitKernel.cc
/usr/local/lib64/src/library/blas/functor/gcn_dgemmSmallMatrices.cc
/usr/local/lib64/src/library/blas/functor/gcn_sgemm.cc               
/usr/local/lib64/src/library/blas/functor/tahiti.cc
/usr/local/lib64/src/library/blas/functor/gcn_sgemmSmallMatrices.cc
/usr/local/lib64/src/library/blas/functor/include/atomic_counter.h                
/usr/local/lib64/src/library/blas/functor/include/gcn_dgemmSmallMatrices.h
/usr/local/lib64/src/library/blas/functor/include/BinaryBuild.h                   
/usr/local/lib64/src/library/blas/functor/include/gcn_sgemm.h
/usr/local/lib64/src/library/blas/functor/include/bonaire.h                       
/usr/local/lib64/src/library/blas/functor/include/gcn_sgemmSmallMatrices.h
/usr/local/lib64/src/library/blas/functor/include/functor_fill.h                  
/usr/local/lib64/src/library/blas/functor/include/gcn_zgemm.h
/usr/local/lib64/src/library/blas/functor/include/functor.h                       
/usr/local/lib64/src/library/blas/functor/include/gpu_dtrsm192.h
/usr/local/lib64/src/library/blas/functor/include/functor_hawaii_dgemm_NT_MN48.h  
/usr/local/lib64/src/library/blas/functor/include/gpu_dtrsm.h
/usr/local/lib64/src/library/blas/functor/include/functor_selector.h              
/usr/local/lib64/src/library/blas/functor/include/hawaii_dgemmChannelConflict.h
/usr/local/lib64/src/library/blas/functor/include/functor_utils.h                 
/usr/local/lib64/src/library/blas/functor/include/hawaii_dgemmSplitKernel.h
/usr/local/lib64/src/library/blas/functor/include/functor_xgemm.h                 
/usr/local/lib64/src/library/blas/functor/include/hawaii.h
/usr/local/lib64/src/library/blas/functor/include/functor_xscal_generic.h         
/usr/local/lib64/src/library/blas/functor/include/hawaii_sgemmBig1024Kernel.h
/usr/local/lib64/src/library/blas/functor/include/functor_xscal.h                 
/usr/local/lib64/src/library/blas/functor/include/hawaii_sgemmBranchKernel.h
/usr/local/lib64/src/library/blas/functor/include/functor_xtrsm.h                 
/usr/local/lib64/src/library/blas/functor/include/hawaii_sgemmSplit64_32.h
/usr/local/lib64/src/library/blas/functor/include/gcn_dgemmCommon.h               
/usr/local/lib64/src/library/blas/functor/include/hawaii_sgemmSplitKernel.h
/usr/local/lib64/src/library/blas/functor/include/gcn_dgemm.h                     
/usr/local/lib64/src/library/blas/functor/include/tahiti.h
/usr/local/lib64/src/library/blas/generic/binary_lookup.cc  
/usr/local/lib64/src/library/blas/generic/kdump.c         
/usr/local/lib64/src/library/blas/generic/solution_assert.c
/usr/local/lib64/src/library/blas/generic/blas_funcs.c      
/usr/local/lib64/src/library/blas/generic/kernel_extra.c  
/usr/local/lib64/src/library/blas/generic/solution_assert.h
/usr/local/lib64/src/library/blas/generic/common2.cc        
/usr/local/lib64/src/library/blas/generic/matrix_dims.c   
/usr/local/lib64/src/library/blas/generic/solution_seq.c
/usr/local/lib64/src/library/blas/generic/common.c          
/usr/local/lib64/src/library/blas/generic/matrix_props.c  
/usr/local/lib64/src/library/blas/generic/solution_seq_make.c
/usr/local/lib64/src/library/blas/generic/events.c          
/usr/local/lib64/src/library/blas/generic/problem_iter.c
/usr/local/lib64/src/library/blas/generic/functor_cache.cc  
/usr/local/lib64/src/library/blas/generic/problem_iter.h
/usr/local/lib64/src/library/blas/gens/asum.cpp              
/usr/local/lib64/src/library/blas/gens/ger_lds.cpp      
/usr/local/lib64/src/library/blas/gens/tile.c
/usr/local/lib64/src/library/blas/gens/axpy_reg.cpp          
/usr/local/lib64/src/library/blas/gens/her2_lds.cpp     
/usr/local/lib64/src/library/blas/gens/tile.h
/usr/local/lib64/src/library/blas/gens/blas_kgen.c           
/usr/local/lib64/src/library/blas/gens/her_lds.cpp      
/usr/local/lib64/src/library/blas/gens/tile_iter.c
/usr/local/lib64/src/library/blas/gens/blas_kgen.h           
/usr/local/lib64/src/library/blas/gens/iamax.cpp        
/usr/local/lib64/src/library/blas/gens/tile_iter.h
/usr/local/lib64/src/library/blas/gens/blas_subgroup.c       
/usr/local/lib64/src/library/blas/gens/init.h           
/usr/local/lib64/src/library/blas/gens/tilemul.c
/usr/local/lib64/src/library/blas/gens/blas_subgroup.h       
/usr/local/lib64/src/library/blas/gens/kprintf.cpp      
/usr/local/lib64/src/library/blas/gens/trmm.c          
/usr/local/lib64/src/library/blas/gens/trmv_reg.cpp
/usr/local/lib64/src/library/blas/gens/copy_reg.cpp          
/usr/local/lib64/src/library/blas/gens/nrm2.cpp         
/usr/local/lib64/src/library/blas/gens/trsm.c
/usr/local/lib64/src/library/blas/gens/decomposition.c       
/usr/local/lib64/src/library/blas/gens/reduction.cpp    
/usr/local/lib64/src/library/blas/gens/trsm_kgen.c
/usr/local/lib64/src/library/blas/gens/dot.cpp               
/usr/local/lib64/src/library/blas/gens/rotg_reg.cpp     
/usr/local/lib64/src/library/blas/gens/trsm_kgen.h
/usr/local/lib64/src/library/blas/gens/fetch.c               
/usr/local/lib64/src/library/blas/gens/rotmg_reg.cpp    
/usr/local/lib64/src/library/blas/gens/trsv_gemv.cpp
/usr/local/lib64/src/library/blas/gens/fetch.h               
/usr/local/lib64/src/library/blas/gens/rotm_reg.cpp     
/usr/local/lib64/src/library/blas/gens/trsv_trtri.cpp
/usr/local/lib64/src/library/blas/gens/gbmv.cpp              
/usr/local/lib64/src/library/blas/gens/scal_reg.cpp     
/usr/local/lib64/src/library/blas/gens/trxm_common.c
/usr/local/lib64/src/library/blas/gens/gemm.c                
/usr/local/lib64/src/library/blas/gens/swap_reg.cpp     
/usr/local/lib64/src/library/blas/gens/trxm_common.h
/usr/local/lib64/src/library/blas/gens/gemm_cached.cpp       
/usr/local/lib64/src/library/blas/gens/symm_cached.cpp  
/usr/local/lib64/src/library/blas/gens/tuned_numbers.c
/usr/local/lib64/src/library/blas/gens/gemm_tail_cached.cpp  
/usr/local/lib64/src/library/blas/gens/symv.c           
/usr/local/lib64/src/library/blas/gens/tuned_numbers.h
/usr/local/lib64/src/library/blas/gens/gemv.c                
/usr/local/lib64/src/library/blas/gens/syr2_lds.cpp     
/usr/local/lib64/src/library/blas/gens/xxmv_common.c
/usr/local/lib64/src/library/blas/gens/gen_helper.c          
/usr/local/lib64/src/library/blas/gens/syr_lds.cpp      
/usr/local/lib64/src/library/blas/gens/xxmv_common.h
/usr/local/lib64/src/library/blas/gens/gen_helper.h          
/usr/local/lib64/src/library/blas/gens/syrxk.c
/usr/local/lib64/src/library/blas/gens/gen_init.c            
/usr/local/lib64/src/library/blas/gens/clTemplates/asum.cl                         
/usr/local/lib64/src/library/blas/gens/clTemplates/rotg.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/axpy.cl                         
/usr/local/lib64/src/library/blas/gens/clTemplates/rotm.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/copy.cl                         
/usr/local/lib64/src/library/blas/gens/clTemplates/rotmg.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/dgemm_gcn_SmallMatrices.cl      
/usr/local/lib64/src/library/blas/gens/clTemplates/scal.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/dgemm_hawai.cl                  
/usr/local/lib64/src/library/blas/gens/clTemplates/sgemm_gcn_bigMatrices.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/dgemm_hawaiiChannelConfilct.cl  
/usr/local/lib64/src/library/blas/gens/clTemplates/sgemm_gcn.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/dgemm_hawaiiSplitKernel.cl      
/usr/local/lib64/src/library/blas/gens/clTemplates/sgemm_gcn_SmallMatrices.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/dgemm_NT_MN48.cl                
/usr/local/lib64/src/library/blas/gens/clTemplates/sgemm_hawaiiSplit64_32.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/dot.cl                          
/usr/local/lib64/src/library/blas/gens/clTemplates/sgemm_hawaiiSplitKernel.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/dtrsm_gpu192.cl                 
/usr/local/lib64/src/library/blas/gens/clTemplates/swap.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/dtrsm_gpu.cl                    
/usr/local/lib64/src/library/blas/gens/clTemplates/symm.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/gbmv.cl                         
/usr/local/lib64/src/library/blas/gens/clTemplates/symm_helper.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/gemm.cl                         
/usr/local/lib64/src/library/blas/gens/clTemplates/syr2.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/gemm_helper.cl                  
/usr/local/lib64/src/library/blas/gens/clTemplates/syr2_her2.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/ger.cl                          
/usr/local/lib64/src/library/blas/gens/clTemplates/syr.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/her2.cl                         
/usr/local/lib64/src/library/blas/gens/clTemplates/syr_her.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/her.cl                         
/usr/local/lib64/src/library/blas/gens/clTemplates/trmv.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/iamax.cl                        
/usr/local/lib64/src/library/blas/gens/clTemplates/trsv.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/nrm2.cl                         
/usr/local/lib64/src/library/blas/gens/clTemplates/trsv_gemv.cl
/usr/local/lib64/src/library/blas/gens/clTemplates/reduction.cl                    
/usr/local/lib64/src/library/blas/gens/clTemplates/zgemm_gcn.cl
/usr/local/lib64/src/library/blas/gens/legacy/blas_kgen_legacy.c   
/usr/local/lib64/src/library/blas/gens/legacy/gen_helper_legacy.h  
/usr/local/lib64/src/library/blas/gens/legacy/trsm_kgen_legacy.c
/usr/local/lib64/src/library/blas/gens/legacy/blas_kgen_legacy.h   
/usr/local/lib64/src/library/blas/gens/legacy/trsm_kgen_legacy.h
/usr/local/lib64/src/library/blas/gens/legacy/blkmul.c             
/usr/local/lib64/src/library/blas/gens/legacy/trmm_img.c           
/usr/local/lib64/src/library/blas/gens/legacy/trsm_lds.c
/usr/local/lib64/src/library/blas/gens/legacy/gemm_img.c           
/usr/local/lib64/src/library/blas/gens/legacy/trmm_lds.c           
/usr/local/lib64/src/library/blas/gens/legacy/trxm_common_legacy.c
/usr/local/lib64/src/library/blas/gens/legacy/gemm_lds.c           
/usr/local/lib64/src/library/blas/gens/legacy/trsm_cached_lds.c    
/usr/local/lib64/src/library/blas/gens/legacy/trxm_common_legacy.h
/usr/local/lib64/src/library/blas/gens/legacy/gen_helper_legacy.c  
/usr/local/lib64/src/library/blas/gens/legacy/trsm_img.c
/usr/local/lib64/src/library/blas/gens/legacy/tests/CMakeLists.txt  
/usr/local/lib64/src/library/blas/gens/legacy/tests/t_blkmul.c
/usr/local/lib64/src/library/blas/gens/tests/CMakeLists.txt  
/usr/local/lib64/src/library/blas/gens/tests/t_tilemul.c
/usr/local/lib64/src/library/blas/include/blas_funcs.h       
/usr/local/lib64/src/library/blas/include/events.h       
/usr/local/lib64/src/library/blas/include/matrix_props.h
/usr/local/lib64/src/library/blas/include/blas_mempat.h      
/usr/local/lib64/src/library/blas/include/kprintf.hpp    
/usr/local/lib64/src/library/blas/include/solution_seq.h
/usr/local/lib64/src/library/blas/include/clblas-internal.h  
/usr/local/lib64/src/library/blas/include/matrix_dims.h  
/usr/local/lib64/src/library/blas/include/xgemm.h
/usr/local/lib64/src/library/blas/specialCases/GemmSpecialCases.cpp
/usr/local/lib64/src/library/blas/specialCases/include/GemmSpecialCases.h
/usr/local/lib64/src/library/blas/trtri/diag_dtrtri_lower_128_16.cpp
/usr/local/lib64/src/library/blas/trtri/diag_dtrtri_upper_128_16.cpp
/usr/local/lib64/src/library/blas/trtri/diag_dtrtri_upper_192_12.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_16_PART1_L.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_16_PART2_L.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_16_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_32_PART1_L.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_32_PART1_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_32_PART2_L.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_32_PART2_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_64_PART1_L.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_64_PART1_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_64_PART2_L.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_64_PART2_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_ABOVE64_PART1_L.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_ABOVE64_PART1_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_ABOVE64_PART2_L.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_ABOVE64_PART2_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_ABOVE64_PART3_L.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_128_ABOVE64_PART3_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_192_12_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_192_24_PART1_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_192_24_PART2_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_192_48_PART1_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_192_48_PART2_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_192_96_PART1_R.cpp
/usr/local/lib64/src/library/blas/trtri/triple_dgemm_update_192_96_PART2_R.cpp
/usr/local/lib64/src/library/blas/trtri/TrtriClKernels.h
/usr/local/lib64/src/library/blas/trtri/TrtriKernelSourceIncludes.cpp
/usr/local/lib64/src/library/blas/trtri/TrtriKernelSourceIncludes.h
/usr/local/lib64/src/samples/clBlasVersion.c    
/usr/local/lib64/src/samples/example_sasum.c   
/usr/local/lib64/src/samples/example_ssbmv.c   
/usr/local/lib64/src/samples/example_stbsv.c
/usr/local/lib64/src/samples/CMakeLists.pack    
/usr/local/lib64/src/samples/example_saxpy.c   
/usr/local/lib64/src/samples/example_sscal.c   
/usr/local/lib64/src/samples/example_stpmv.c
/usr/local/lib64/src/samples/CMakeLists.txt     
/usr/local/lib64/src/samples/example_scopy.c   
/usr/local/lib64/src/samples/example_sspmv.c   
/usr/local/lib64/src/samples/example_stpsv.c
/usr/local/lib64/src/samples/example_chbmv.c    
/usr/local/lib64/src/samples/example_sdot.c    
/usr/local/lib64/src/samples/example_sspr2.c   
/usr/local/lib64/src/samples/example_strmm.c
/usr/local/lib64/src/samples/example_chemm.cpp  
/usr/local/lib64/src/samples/example_sgbmv.c   
/usr/local/lib64/src/samples/example_sspr.c    
/usr/local/lib64/src/samples/example_strmv.c
/usr/local/lib64/src/samples/example_cher2k.c   
/usr/local/lib64/src/samples/example_sgemm.c   
/usr/local/lib64/src/samples/example_sswap.c   
/usr/local/lib64/src/samples/example_strsm.c
/usr/local/lib64/src/samples/example_cher.c     
/usr/local/lib64/src/samples/example_sgemv.c   
/usr/local/lib64/src/samples/example_ssymm.c   
/usr/local/lib64/src/samples/example_strsv.c
/usr/local/lib64/src/samples/example_cherk.cpp  
/usr/local/lib64/src/samples/example_sger.c    
/usr/local/lib64/src/samples/example_ssymv.c   
/usr/local/lib64/src/samples/example_zhemv.cpp
/usr/local/lib64/src/samples/example_chpmv.c    
/usr/local/lib64/src/samples/example_snrm2.c   
/usr/local/lib64/src/samples/example_ssyr2.c   
/usr/local/lib64/src/samples/example_zher2.c
/usr/local/lib64/src/samples/example_chpr.c     
/usr/local/lib64/src/samples/example_srot.c    
/usr/local/lib64/src/samples/example_ssyr2k.c  
/usr/local/lib64/src/samples/example_zhpr2.c
/usr/local/lib64/src/samples/example_csscal.c   
/usr/local/lib64/src/samples/example_srotg.c   
/usr/local/lib64/src/samples/example_ssyr.c
/usr/local/lib64/src/samples/example_dtrmv.c    
/usr/local/lib64/src/samples/example_srotm.c   
/usr/local/lib64/src/samples/example_ssyrk.c
/usr/local/lib64/src/samples/example_isamax.c   
/usr/local/lib64/src/samples/example_srotmg.c  
/usr/local/lib64/src/samples/example_stbmv.c
/usr/local/lib64/src/scripts/perf/blasPerformanceTesting.py  
/usr/local/lib64/src/scripts/perf/errorHandler.py        
/usr/local/lib64/src/scripts/perf/performanceUtility.py
/usr/local/lib64/src/scripts/perf/CMakeLists.txt             
/usr/local/lib64/src/scripts/perf/measurePerformance.py  
/usr/local/lib64/src/scripts/perf/plotPerformance.py
/usr/local/lib64/src/tests/BasicRoutines.cpp   
/usr/local/lib64/src/tests/CMakeLists.txt                 
/usr/local/lib64/src/tests/gtest.cmake
/usr/local/lib64/src/tests/BlasBase.cpp        
/usr/local/lib64/src/tests/cmdline.c                      
/usr/local/lib64/src/tests/blas.c              
/usr/local/lib64/src/tests/common.cpp                     
/usr/local/lib64/src/tests/blas-cblas.c        
/usr/local/lib64/src/tests/copyTestDependencies.cmake.in  
/usr/local/lib64/src/tests/timer.c
/usr/local/lib64/src/tests/blas-wrapper.cpp    
/usr/local/lib64/src/tests/clBLAS-wrapper.cpp  
/usr/local/lib64/src/tests/include/asum.h            
/usr/local/lib64/src/tests/include/copy.h            
/usr/local/lib64/src/tests/include/hemm.h    
/usr/local/lib64/src/tests/include/nrm2.h   
/usr/local/lib64/src/tests/include/symm.h         
/usr/local/lib64/src/tests/include/tpmv.h
/usr/local/lib64/src/tests/include/axpy.h            
/usr/local/lib64/src/tests/include/dotc.h            
/usr/local/lib64/src/tests/include/hemv.h    
/usr/local/lib64/src/tests/include/rotg.h   
/usr/local/lib64/src/tests/include/symv.h         
/usr/local/lib64/src/tests/include/tpsv.h
/usr/local/lib64/src/tests/include/BlasBase.h        
/usr/local/lib64/src/tests/include/dot.h             
/usr/local/lib64/src/tests/include/her2.h    
/usr/local/lib64/src/tests/include/rot.h    
/usr/local/lib64/src/tests/include/syr2.h         
/usr/local/lib64/src/tests/include/trmm.h
/usr/local/lib64/src/tests/include/blas-cblas.h      
/usr/local/lib64/src/tests/include/ExtraTestSizes.h  
/usr/local/lib64/src/tests/include/her2k.h   
/usr/local/lib64/src/tests/include/rotmg.h  
/usr/local/lib64/src/tests/include/syr2k.h        
/usr/local/lib64/src/tests/include/trmv.h
/usr/local/lib64/src/tests/include/blas-internal.h   
/usr/local/lib64/src/tests/include/gbmv.h            
/usr/local/lib64/src/tests/include/her.h     
/usr/local/lib64/src/tests/include/rotm.h   
/usr/local/lib64/src/tests/include/syr.h          
/usr/local/lib64/src/tests/include/trsm.h
/usr/local/lib64/src/tests/include/blas-math.h       
/usr/local/lib64/src/tests/include/gemm-2.h          
/usr/local/lib64/src/tests/include/herk.h    
/usr/local/lib64/src/tests/include/sbmv.h   
/usr/local/lib64/src/tests/include/syrk.h         
/usr/local/lib64/src/tests/include/trsv.h
/usr/local/lib64/src/tests/include/blas-random.h     
/usr/local/lib64/src/tests/include/gemm.h            
/usr/local/lib64/src/tests/include/hpmv.h    
/usr/local/lib64/src/tests/include/scal.h   
/usr/local/lib64/src/tests/include/tbmv.h
/usr/local/lib64/src/tests/include/blas-wrapper.h    
/usr/local/lib64/src/tests/include/gemv.h            
/usr/local/lib64/src/tests/include/hpr2.h    
/usr/local/lib64/src/tests/include/spmv.h   
/usr/local/lib64/src/tests/include/tbsv.h
/usr/local/lib64/src/tests/include/clBLAS-wrapper.h  
/usr/local/lib64/src/tests/include/gerc.h            
/usr/local/lib64/src/tests/include/hpr.h     
/usr/local/lib64/src/tests/include/spr2.h   
/usr/local/lib64/src/tests/include/testDG.h
/usr/local/lib64/src/tests/include/cmdline.h         
/usr/local/lib64/src/tests/include/ger.h             
/usr/local/lib64/src/tests/include/iamax.h   
/usr/local/lib64/src/tests/include/spr.h    
/usr/local/lib64/src/tests/include/test-limits.h
/usr/local/lib64/src/tests/include/common.h          
/usr/local/lib64/src/tests/include/hbmv.h            
/usr/local/lib64/src/tests/include/matrix.h  
/usr/local/lib64/src/tests/include/swap.h   
/usr/local/lib64/src/tests/include/timer.h
/usr/local/lib64/src/tests/performance/BlasBase-perf.cpp  
/usr/local/lib64/src/tests/performance/perf-herk.cpp            
/usr/local/lib64/src/tests/performance/perf-spr.cpp
/usr/local/lib64/src/tests/performance/perf-asum.cpp      
/usr/local/lib64/src/tests/performance/perf-hpmv.cpp            
/usr/local/lib64/src/tests/performance/perf-swap.cpp
/usr/local/lib64/src/tests/performance/perf-axpy.cpp      
/usr/local/lib64/src/tests/performance/perf-hpr2.cpp            
/usr/local/lib64/src/tests/performance/perf-symm.cpp
/usr/local/lib64/src/tests/performance/perf-copy.cpp      
/usr/local/lib64/src/tests/performance/perf-hpr.cpp             
/usr/local/lib64/src/tests/performance/perf-symv.cpp
/usr/local/lib64/src/tests/performance/perf-dotc.cpp      
/usr/local/lib64/src/tests/performance/perf-iamax.cpp           
/usr/local/lib64/src/tests/performance/perf-syr2.cpp
/usr/local/lib64/src/tests/performance/perf-dot.cpp       
/usr/local/lib64/src/tests/performance/perf-nrm2.cpp            
/usr/local/lib64/src/tests/performance/perf-syr2k.cpp
/usr/local/lib64/src/tests/performance/perf-gbmv.cpp      
/usr/local/lib64/src/tests/performance/PerformanceRecorder.cpp  
/usr/local/lib64/src/tests/performance/perf-syr.cpp
/usr/local/lib64/src/tests/performance/perf-gemm2.cpp     
/usr/local/lib64/src/tests/performance/PerformanceRecorder.h    
/usr/local/lib64/src/tests/performance/perf-syrk.cpp
/usr/local/lib64/src/tests/performance/perf-gemm.cpp      
/usr/local/lib64/src/tests/performance/PerformanceTest.cpp     
/usr/local/lib64/src/tests/performance/perf-tbmv.cpp
/usr/local/lib64/src/tests/performance/perf-gemv.cpp      
/usr/local/lib64/src/tests/performance/PerformanceTest.h        
/usr/local/lib64/src/tests/performance/perf-tbsv.cpp
/usr/local/lib64/src/tests/performance/perf-gerc.cpp      
/usr/local/lib64/src/tests/performance/perf-rot.cpp             
/usr/local/lib64/src/tests/performance/perf-tpmv.cpp
/usr/local/lib64/src/tests/performance/perf-ger.cpp       
/usr/local/lib64/src/tests/performance/perf-rotg.cpp            
/usr/local/lib64/src/tests/performance/perf-tpsv.cpp
/usr/local/lib64/src/tests/performance/perf-hbmv.cpp      
/usr/local/lib64/src/tests/performance/perf-rotm.cpp            
/usr/local/lib64/src/tests/performance/perf-trmm.cpp
/usr/local/lib64/src/tests/performance/perf-hemm.cpp      
/usr/local/lib64/src/tests/performance/perf-rotmg.cpp           
/usr/local/lib64/src/tests/performance/perf-trmv.cpp
/usr/local/lib64/src/tests/performance/perf-hemv.cpp      
/usr/local/lib64/src/tests/performance/perf-sbmv.cpp            
/usr/local/lib64/src/tests/performance/perf-trsm.cpp
/usr/local/lib64/src/tests/performance/perf-her2.cpp      
/usr/local/lib64/src/tests/performance/perf-scal.cpp            
/usr/local/lib64/src/tests/performance/perf-trsv.cpp
/usr/local/lib64/src/tests/performance/perf-her2k.cpp     
/usr/local/lib64/src/tests/performance/perf-spmv.cpp            
/usr/local/lib64/src/tests/performance/test-performance.cpp
/usr/local/lib64/src/tests/performance/perf-her.cpp       
/usr/local/lib64/src/tests/performance/perf-spr2.cpp            
/usr/local/lib64/src/tests/performance/TrxmPerformanceTest.cpp
/usr/local/lib64/src/tests/correctness/BlasBase-corr.cpp  
/usr/local/lib64/src/tests/correctness/corr-hbmv.cpp   
/usr/local/lib64/src/tests/correctness/corr-rotm.cpp   
/usr/local/lib64/src/tests/correctness/corr-tbmv.cpp
/usr/local/lib64/src/tests/correctness/blas-lapack.c      
/usr/local/lib64/src/tests/correctness/corr-hemm.cpp   
/usr/local/lib64/src/tests/correctness/corr-rotmg.cpp  
/usr/local/lib64/src/tests/correctness/corr-tbsv.cpp
/usr/local/lib64/src/tests/correctness/blas-lapack.h      
/usr/local/lib64/src/tests/correctness/corr-hemv.cpp   
/usr/local/lib64/src/tests/correctness/corr-sbmv.cpp   
/usr/local/lib64/src/tests/correctness/corr-tpmv.cpp
/usr/local/lib64/src/tests/correctness/corr-asum.cpp      
/usr/local/lib64/src/tests/correctness/corr-her2.cpp   
/usr/local/lib64/src/tests/correctness/corr-scal.cpp   
/usr/local/lib64/src/tests/correctness/corr-tpsv.cpp
/usr/local/lib64/src/tests/correctness/corr-axpy.cpp      
/usr/local/lib64/src/tests/correctness/corr-her2k.cpp  
/usr/local/lib64/src/tests/correctness/corr-spmv.cpp   
/usr/local/lib64/src/tests/correctness/corr-trmm.cpp
/usr/local/lib64/src/tests/correctness/corr-copy.cpp      
/usr/local/lib64/src/tests/correctness/corr-her.cpp    
/usr/local/lib64/src/tests/correctness/corr-spr2.cpp   
/usr/local/lib64/src/tests/correctness/corr-trmv.cpp
/usr/local/lib64/src/tests/correctness/corr-dotc.cpp      
/usr/local/lib64/src/tests/correctness/corr-herk.cpp   
/usr/local/lib64/src/tests/correctness/corr-spr.cpp    
/usr/local/lib64/src/tests/correctness/corr-trsm.cpp
/usr/local/lib64/src/tests/correctness/corr-dot.cpp       
/usr/local/lib64/src/tests/correctness/corr-hpmv.cpp   
/usr/local/lib64/src/tests/correctness/corr-swap.cpp   
/usr/local/lib64/src/tests/correctness/corr-trsv.cpp
/usr/local/lib64/src/tests/correctness/corr-gbmv.cpp      
/usr/local/lib64/src/tests/correctness/corr-hpr2.cpp   
/usr/local/lib64/src/tests/correctness/corr-symm.cpp   
/usr/local/lib64/src/tests/correctness/delta.h
/usr/local/lib64/src/tests/correctness/corr-gemm2.cpp     
/usr/local/lib64/src/tests/correctness/corr-hpr.cpp    
/usr/local/lib64/src/tests/correctness/corr-symv.cpp   
/usr/local/lib64/src/tests/correctness/tcase-filter.cpp
/usr/local/lib64/src/tests/correctness/corr-gemm.cpp      
/usr/local/lib64/src/tests/correctness/corr-iamax.cpp  
/usr/local/lib64/src/tests/correctness/corr-syr2.cpp   
/usr/local/lib64/src/tests/correctness/tcase-filter.h
/usr/local/lib64/src/tests/correctness/corr-gemv.cpp      
/usr/local/lib64/src/tests/correctness/corr-nrm2.cpp   
/usr/local/lib64/src/tests/correctness/corr-syr2k.cpp  
/usr/local/lib64/src/tests/correctness/test-correctness.cpp
/usr/local/lib64/src/tests/correctness/corr-gerc.cpp      
/usr/local/lib64/src/tests/correctness/corr-rot.cpp    
/usr/local/lib64/src/tests/correctness/corr-syr.cpp    
/usr/local/lib64/src/tests/correctness/trsm-delta.h
/usr/local/lib64/src/tests/correctness/corr-ger.cpp       
/usr/local/lib64/src/tests/correctness/corr-rotg.cpp   
/usr/local/lib64/src/tests/correctness/corr-syrk.cpp   
/usr/local/lib64/src/tests/correctness/trsv-delta.h
/usr/local/lib64/src/tests/functional/BlasBase-func.cpp  
/usr/local/lib64/src/tests/functional/func-event.cpp  
/usr/local/lib64/src/tests/functional/func-images.cpp  
/usr/local/lib64/src/tests/functional/func-thread.cpp
/usr/local/lib64/src/tests/functional/func-error.cpp     
/usr/local/lib64/src/tests/functional/func.h          
/usr/local/lib64/src/tests/functional/func-queue.cpp   
/usr/local/lib64/src/tests/functional/test-functional.cpp
/usr/local/lib64/src/wrappers/python/pyclBLAS.pxd  
/usr/local/lib64/src/wrappers/python/pyclBLAS.pyx  
/usr/local/lib64/src/wrappers/python/README.txt  
/usr/local/lib64/src/wrappers/python/setup.py
/usr/local/bin/clBLAS-tune
/usr/local/include/clAmdBlas.h
/usr/local/include/clAmdBlas.version.h
/usr/local/include/clBLAS-complex.h
/usr/local/include/clBLAS.h
/usr/local/include/clBLAS.version.h
/usr/local/lib64/cmake/clBLAS/clBLASConfig.cmake
/usr/local/lib64/cmake/clBLAS/clBLASConfigVersion.cmake
/usr/local/lib64/cmake/clBLAS/clBLASTargets-debug.cmake
/usr/local/lib64/cmake/clBLAS/clBLASTargets.cmake
/usr/local/lib64/libclBLAS.so
/usr/local/lib64/libclBLAS.so.2
/usr/local/lib64/libclBLAS.so.2.10.0
/usr/local/lib64/pkgconfig/clBLAS.pc
/usr/local/lib64/src/library/blas/AutoGemm/.gitignore
/usr/local/lib64/src/library/blas/AutoGemm/__pycache__/AutoGemmParameters.cpython-35.pyc
/usr/local/lib64/src/library/blas/AutoGemm/__pycache__/Common.cpython-35.pyc
/usr/local/lib64/src/library/blas/AutoGemm/__pycache__/Includes.cpython-35.pyc
/usr/local/lib64/src/library/blas/AutoGemm/__pycache__/KernelOpenCL.cpython-35.pyc
/usr/local/lib64/src/library/blas/AutoGemm/__pycache__/KernelParameters.cpython-35.pyc
/usr/local/lib64/src/library/blas/AutoGemm/__pycache__/KernelSelection.cpython-35.pyc

%changelog
* Thu Aug 11 2016 Benson Muite <benson_muite@emailplus.org>
- Initial version of package
